name: Run Appium Test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Appium
        run: npm install -g appium@2
          
      - name: Display Appium Version
        run: appium -v
        
      - name: Install UIAutomator2 driver
        run: appium driver install uiautomator2

      - name: Set up Emulator
        run: |
          echo no | %ANDROID_HOME%\tools\bin\avdmanager create avd -n emulatortest2 -k "system-images;android-29;google_apis;x86"
          %ANDROID_HOME%\emulator\emulator -avd emulatortest2 -no-audio -no-window
          adb devices

      - name: Run Appium Tests
        run: mvn -Dtest=appium.MobileTesting.Logintest test
