name: Launch Android Emulator

on:
  workflow_dispatch:

jobs:
  launchemulator:
    runs-on: macos-latest

    steps:
      - name: Install Android SDK
        run: |
          echo y | sdkmanager "platform-tools" "platforms;android-29" "system-images;android-29;google_apis;x86"
          echo no | avdmanager create avd -n Pixel_AVD -k "system-images;android-29;google_apis;x86"

      - name: Launch emulator
        run: |
          emulator -avd Pixel_AVD -no-window -no-audio

      - name: Wait for emulator to start
        run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - name: List devices
        run: adb devices
