name: Launch Android Emulator

on:
  workflow_dispatch:

jobs:
  emulator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Download Android SDK tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O android-sdk-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip -q android-sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$HOME/android-sdk/tools:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept Android licenses
        run: yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install system image
        run: $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "system-images;android-29;google_apis;x86"

      - name: Create emulator
        run: echo no | $HOME/android-sdk/cmdline-tools/latest/bin/avdmanager create avd -n emulatortest -k "system-images;android-29;google_apis;x86"

      - name: Launch emulator
        run: $HOME/android-sdk/emulator/emulator -avd emulatortest -no-audio -no-window
