name: Launch Android Emulator

on:
  workflow_dispatch:

jobs:
  launch-emulator:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Android SDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Android SDK
        run: |
          wget -q https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip -O android-sdk-tools.zip
          unzip -qq android-sdk-tools.zip -d $HOME/android-sdk
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$HOME/android-sdk/tools/bin:$PATH" >> $GITHUB_ENV

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Create Android emulator
        run: echo no | avdmanager create avd -n emulatortest2 -k "system-images;android-29;google_apis;x86"

      - name: Launch Android emulator
        run: $ANDROID_HOME/emulator/emulator -avd emulatortest2 -no-audio -no-window &
