name: List Available Devices

on:
  workflow_dispatch:

jobs:
  list-devices:
    runs-on: macos-latest

    steps:
      - name: Set up Android SDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Android SDK
        run: |
          wget -q https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip -O android-sdk-tools.zip
          unzip -qq android-sdk-tools.zip -d $HOME/android-sdk
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$HOME/android-sdk/tools/bin:$PATH" >> $GITHUB_ENV

      - name: List available devices
        run: |
          echo "Available devices:"
          $ANDROID_HOME/tools/bin/sdkmanager --list | grep -E "system-images;android-[0-9]+;[^;]*;[^;]*$" | cut -d '|' -f 1 | sed 's/Available Packages://'
