name: Appium test 

on:
  workflow_dispatch:
    

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
       - name: Set up Java 11
         uses: actions/setup-java@v4
         with:
            distribution: 'temurin'
            java-version: '21'
            
       - name: Checkout code
         uses: actions/checkout@v3
        
       - name: Set up Appium
         run: |
           npm install -g appium@2
           appium -v
           appium &>/dev/null &

       - name: Set up UIAutomator2
         run: |
          appium driver install UIAutomator2
  
       - name: run tests
         uses: reactivecircus/android-emulator-runner@v2
         with:
          api-level: 29
          script: |
                  appium driver --list installed
                  mvn clean test
