name: Launch Android Emulator

on:
  workflow_dispatch:

jobs:
  launch-emulator:
    runs-on: macos-latest

    steps:
      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          cd $HOME/android-sdk/cmdline-tools/latest
          curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-mac-6609375_latest.zip
          unzip -qq tools.zip
          rm -f tools.zip

      - name: Accept Android licenses
        run: yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Create Android emulator
        run: echo no | $HOME/android-sdk/cmdline-tools/latest/bin/avdmanager create avd -n emulatortest2 -k "syste
