name: Launch Android Emulator

on:
  workflow_dispatch:

jobs:
  launch-emulator:
    runs-on: macos-latest

    steps:
      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-mac-6609375_latest.zip -O tools.zip
          unzip -qq tools.zip
          mv cmdline-tools/* latest/
          rm -rf cmdline-tools tools.zip

      - name: Accept Android licenses
        run: yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Create Android emulator
        run: echo no | $HOME/android-sdk/cmdline-tools/latest/bin/avdmanager create avd -n emulatortest2 -k "system-images;android-29;google_apis;x86"

      - name: Launch Android emulator
        run: $HOME/android-sdk/cmdline-tools/latest/bin/emulator -avd emulatortest2 -no-audio -no-window &
