name: Launch Emulator

on:
  workflow_dispatch:

jobs:
  launchemulator:
    runs-on: macos-latest

    steps:
      - name: Check Android SDK Path
        run: echo $ANDROID_HOME

      - name: List available system images
        run: $ANDROID_HOME/tools/bin/sdkmanager --list

      - name: Debug Emulator Setup
        run: |
          echo "Creating AVD..."
          echo no | $ANDROID_HOME/tools/bin/avdmanager create avd -n emulatortest2 -k "system-images;android-30;google_apis_playstore;x86_64"
          # Rest of your emulator setup and testing steps...

